name: Autograding Tests
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev shelltestrunner texlive-latex-base latexmk
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    - name: Build
      run: cmake --build ${{github.workspace}}/build 
    - name: Basic Tests
      id: basic-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Basic Tests
        setup-command: ''
        command: ctest -R BasicTests --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 30
    - name: Basic Errors
      id: basic-errors
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Basic Errors
        setup-command: ''
        command: ctest -R BasicErrors --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 5
    - name: Builtin Tests
      id: builtin-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Builtin Tests
        setup-command: ''
        command: ctest -R BuiltinTests --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 15
    - name: Environment Tests
      id: environment-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Environment Tests
        setup-command: ''
        command: ctest -R EnvironmentTests --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 15
    - name: Redirection Tests
      id: redirection-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Redirection Tests
        setup-command: ''
        command: ctest -R RedirectionTests --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 15
    - name: Redirection Errors
      id: redirection-errors
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Redirection Errors
        setup-command: ''
        command: ctest -R RedirectionErrors --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 10
    - name: Corner Tests
      id: corner-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Corner Tests
        setup-command: ''
        command: ctest -R CornerTests --test-dir ${{github.workspace}}/build
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BASIC-TESTS_RESULTS: "${{steps.basic-tests.outputs.result}}"
        BASIC-ERRORS_RESULTS: "${{steps.basic-errors.outputs.result}}"
        BUILTIN-TESTS_RESULTS: "${{steps.builtin-tests.outputs.result}}"
        ENVIRONMENT-TESTS_RESULTS: "${{steps.environment-tests.outputs.result}}"
        REDIRECTION-TESTS_RESULTS: "${{steps.redirection-tests.outputs.result}}"
        REDIRECTION-ERRORS_RESULTS: "${{steps.redirection-errors.outputs.result}}"
        CORNER-TESTS_RESULTS: "${{steps.corner-tests.outputs.result}}"
      with:
        runners: basic-tests,basic-errors,builtin-tests,environment-tests,redirection-tests,redirection-errors,corner-tests
